development:
  adapter: postgresql
  database: clinica_canela_development
  host: localhost

test:
    adapter: postgresql
    database: clinica_canela_test
    host: localhost

production:
    adapter: postgresql
    database: clinica_canela_production
    host: localhost